//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public int EmpEducationId { get; set; }
        public int EmployeeId { get; set; }
        public string InstituteName { get; set; }
        public int InstituteType { get; set; }
        public decimal Percentage { get; set; }
        public System.DateTime JoinedOn { get; set; }
        public System.DateTime PassedOn { get; set; }
        public int IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
