//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExperience
    {
        public int EmpExperienceId { get; set; }
        public int EmployeeId { get; set; }
        public string CompanyName { get; set; }
        public string Position { get; set; }
        public System.DateTime JoinedOn { get; set; }
        public Nullable<System.DateTime> LeftOn { get; set; }
        public int IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
