//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipTag
    {
        public int InternTagId { get; set; }
        public int InternshipId { get; set; }
        public int TagId { get; set; }
    
        public virtual Internship Internship { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
