//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Internship()
        {
            this.InternshipCities = new HashSet<InternshipCity>();
            this.InternshipQuestions = new HashSet<InternshipQuestion>();
            this.InternshipSkills = new HashSet<InternshipSkill>();
            this.InternshipTags = new HashSet<InternshipTag>();
            this.InternshipApplications = new HashSet<InternshipApplication>();
        }
    
        public int InternshipId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime PostedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public int MinStipend { get; set; }
        public Nullable<int> MaxStipend { get; set; }
        public Nullable<int> PostsAvailable { get; set; }
        public int IsWFHAvailable { get; set; }
        public int IsPartTimeAvailable { get; set; }
        public int JobOffer { get; set; }
        public int IsActicve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipCity> InternshipCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipQuestion> InternshipQuestions { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipSkill> InternshipSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipTag> InternshipTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipApplication> InternshipApplications { get; set; }
    }
}
