//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobQuestion
    {
        public int JobQuestionId { get; set; }
        public int JobId { get; set; }
        public string Question { get; set; }
        public int IsActive { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
