//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int LookupId { get; set; }
        public int LookUpCategory { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ShowOrder { get; set; }
    }
}
