//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MakeMyJobsEntities : DbContext
    {
        public MakeMyJobsEntities()
            : base("name=MakeMyJobsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentDocument> StudentDocuments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeExperience> EmployeeExperiences { get; set; }
        public virtual DbSet<EmployeeEducation> EmployeeEducations { get; set; }
        public virtual DbSet<Corporate> Corporates { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<JobCity> JobCities { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobQuestion> JobQuestions { get; set; }
        public virtual DbSet<InternshipCity> InternshipCities { get; set; }
        public virtual DbSet<InternshipQuestion> InternshipQuestions { get; set; }
        public virtual DbSet<Internship> Internships { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<JobTag> JobTags { get; set; }
        public virtual DbSet<JobSkill> JobSkills { get; set; }
        public virtual DbSet<InternshipSkill> InternshipSkills { get; set; }
        public virtual DbSet<InternshipTag> InternshipTags { get; set; }
        public virtual DbSet<CorporateDocument> CorporateDocuments { get; set; }
        public virtual DbSet<EmployeeDocument> EmployeeDocuments { get; set; }
        public virtual DbSet<InternshipApplication> InternshipApplications { get; set; }
        public virtual DbSet<JobApplication> JobApplications { get; set; }
        public virtual DbSet<InternshipAnswer> InternshipAnswers { get; set; }
        public virtual DbSet<JobAnswer> JobAnswers { get; set; }
    }
}
