//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostCity
    {
        public int PostCityId { get; set; }
        public int PostId { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Post Post { get; set; }
    }
}
