//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostAnswer
    {
        public int AnswerId { get; set; }
        public int UserId { get; set; }
        public int PostId { get; set; }
        public int PostQuestionId { get; set; }
        public string Answer { get; set; }
    
        public virtual PostQuestion PostQuestion { get; set; }
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
    }
}
