//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeMyJobsAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CollegeName { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Resume { get; set; }
        public System.DateTime DateJoined { get; set; }
        public string Address { get; set; }
        public int State { get; set; }
        public int Country { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual State State1 { get; set; }
        public virtual User User { get; set; }
    }
}
